# Top-level configuration
name = "syncify"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

observability = { enabled = true}
placement = { mode = "smart" }
assets = { directory = "./src", binding = "assets" }

main = "./src/worker.js"

[limits]
cpu_ms = 2000
