# Top-level configuration
name = "syncify"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

observability = { enabled = true }
placement = { mode = "smart" }
logpush = true

assets = { directory = "./src/web", binding = "src" }

main = "./src/web/worker.ts"

[durable_objects]
bindings = [
    { name = "rooms", class_name = "Room"},
    { name = "users", class_name = "User"}
]

[limits]
cpu_ms = 20000

[[kv_namespaces]]
binding = "kv"
id = "9e15917973e94c38970d8836e8e2bfcb"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Room", "User"]

[vars]
USER_ACCESS_TOKEN_MAX_AGE = "1d"
USER_COOKIE_MAX_AGE = "86400"

ROOM_ACCESS_TOKEN_MAX_AGE = "1d"
ROOM_COOKIE_MAX_AGE = "86400"