# Top-level configuration
name = "syncify"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

observability = { enabled = true}
placement = { mode = "smart" }

assets = { directory = "./src/web", binding = "assets" }

main = "./src/web/worker.mjs"

[durable_objects]
bindings = [
    { name = "rooms", class_name = "Room"},
    { name = "users", class_name = "User"}
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = []

[limits]
cpu_ms = 2000