name: Backend Client or Server Side Bug
description: Template for reporting bugs relating to Client Side or Server Side features of the Syncify Site or the Syncify extension for Spicetify
title: "[Priority] [Website/Extension] Description of the Problem"
labels: ["bug","HTTP error","Unexpected Behavior"]
assignees: 
  - 'ginocchio'

body:
  - type: markdown
    attributes:
      value: |
        **Bug Description**
        Please provide a clear and precise description of the bug you encountered.

  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Briefly describe the bug...

  - type: markdown
    attributes:
      value: |
        **To Reproduce**
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Perform the action that causes the bug
        4. Observe the incorrect behavior

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: Describe the steps to reproduce the issue...

  - type: markdown
    attributes:
      value: |
        **Expected Behavior**
        A clear and concise description of what you expected to happen.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe what you expected to happen...

  - type: markdown
    attributes:
      value: |
        **Environment**
        Please provide details about your environment:
        - OS: [e.g. Windows, macOS, Linux, Android, iOS]
        - Browser: [e.g. Chrome, Brave, Safari, Firefox, Edge]
        
        - Syncify Version: [e.g. 1.0.0]
        - Spicetify Version: [eg. 1.0.0]
        - Syncify Extension Version: [eg. 1.0.0]

  - type: textarea
    id: environment-info
    attributes:
      label: Environment Information
      description: Please provide details about your environment.
      placeholder: OS, Browser, Versions...

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
