name: HTML/CSS Visual Bug Report
description: Section where it is possible to send feedback on visual bugs relating to the site's pages
title: "Visual Bug on [Page /user,/room,/join,ecc.]"
labels: ["css","html","visual issue"]
projects: ["Syncify Website", "Spicetify Extension"]
assignees:
  - ildesh
body:
  - type: markdown
    attributes:
      value: |
        # HTML/CSS Visual Bug Report

        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.

        **Required fields are marked with an asterisk (*)**

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? *
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce *
      description: Please describe the steps to reproduce the bug.
      placeholder: 1. Go to page... 2. Click on...
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
  - type: dropdown
    id: device
    attributes:
      label: Device
      options:
        - Desktop
        - Mobile
        - Tablet
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Other
  - type: input
    id: other-os
    attributes:
      label: Other Operating System
      description: If you selected "Other", please specify the operating system.
      placeholder: Enter the name of your operating system...
  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: input
    id: other-browser
    attributes:
      label: Other Browser
      description: If you selected "Other", please specify the browser.
      placeholder: Enter the name of your browser...
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please provide links to screenshots that help illustrate the issue.
      placeholder: Provide links to screenshots...
  - type: markdown
    attributes:
      value: |
        ## Thank you!

        We appreciate your feedback and will look into the issue as soon as possible.
